### ISSUE TITLE
New ReadMe

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#982]
Make new design/layout for Readme taking inspiration from the current [ReadMe](https://github.com/swapnilsparsh/30DaysOfJavaScript/blob/master/README.md)

**Comment by piyushmishraa** [comment]
hello @swapnilsparsh  sir, its Piyush Mishra ,a sophomore from kiet group of institutions, participating in IWOC 2023.It would be my pleasure to contribute to this issue and create a new a design for your ReadMe file. I'll be changing the layout to make it look more attractive  while maintaining   a professional  look.
 I can also add cool graphics depending on the fact if its needed or not. 
 I'll also add screenshots of UI your most starred repos so that people already get the idea of they are gonna see without opening the code and rendering it. I request you to please assign this issue to me.
THANK YOU

**Comment by swapnilsparsh** [comment]
@piyushmishraa Work on this issue, keep the Readme as much simple and should have a clean UX, dont include screenshots of every projects in Readme as there are 150+ projects.

**Comment by piyushmishraa** [comment]
Got it 👍 @swapnilsparsh sir
